version: '3.3'

networks:
  frontend:
  backend:

volumes:
  pgdata:
  opdata:

services:
  db:
    image: postgres:13
    restart: unless-stopped
    stop_grace_period: "3s"
    volumes:
      - "${PGDATA:-pgdata}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p4ssw0rd}
      POSTGRES_DB: openproject
    networks:
      - backend

  cache:
    image: memcached
    restart: unless-stopped
    networks:
      - backend

  proxy:
    build:
      context: ./proxy
      args:
        APP_HOST: web
    image: openproject/proxy
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:80"
    depends_on:
      - web
    networks:
      - frontend

  web:
    image: openproject/openproject:${TAG:-16-slim}
    restart: unless-stopped
    command: "./docker/prod/web"
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-false}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-localhost:8080}"
      OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-false}"
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: ${RAILS_MIN_THREADS:-4}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-16}
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
      # Custom icon overlays (uncomment after creating files in custom-assets/)
      - "./custom-assets/logo_openproject.png:/app/app/assets/images/logo_openproject.png:ro"
      - "./custom-assets/icon_logo.svg:/app/app/assets/images/icon_logo.svg:ro"
      - "./custom-assets/icon_logo_white.svg:/app/app/assets/images/icon_logo_white.svg:ro"
      - "./custom-assets/favicon.ico:/app/app/assets/images/favicon.ico:ro"
      - "./custom-assets/apple-touch-icon-120x120.png:/app/app/assets/images/apple-touch-icon-120x120.png:ro"
      - "./custom-assets/logo_openproject_narrow.svg:/app/app/assets/images/logo_openproject_narrow.svg:ro"
      # Additional logo variants in source assets
      - "./custom-assets/logo_openproject_white_big.png:/app/app/assets/images/logo_openproject_white_big.png:ro"
      # Also replace precompiled assets (Rails asset pipeline)
      - "./custom-assets/logo_openproject.png:/app/public/assets/logo_openproject-0ac721deb10b0ac88e34c3a066dc8ce283e9d2601c805ae71fc8dc9548fc0582.png:ro"
      - "./custom-assets/icon_logo.svg:/app/public/assets/icon_logo-955af4346e973d13afd9f5a3d0d4c63f8002be1125bcd41d8036ff67ee1cdd51.svg:ro"
      - "./custom-assets/icon_logo_white.svg:/app/public/assets/icon_logo_white-8e3e74afd4629f3f6fed8e229bbc0dfd926fc196d8b8d0f7bf3be3eca9574fb7.svg:ro"
      - "./custom-assets/logo_openproject_narrow.svg:/app/public/assets/logo_openproject_narrow-b109a77c87bd36817399515b9b09c508e8beaba76a57f2c40fd484d8aa25fa15.svg:ro"
      # Additional logo variants that might be used in the interface
      - "./custom-assets/logo_openproject_white_big.png:/app/public/assets/logo_openproject_white_big-2c6d79fa03613154cf6bd67c622dbae5b93ed3199e0e7332d96b6f8ec21f85a1.png:ro"
      - "./custom-assets/logo_openproject.png:/app/public/assets/styleguide/logo_openproject-0ac721deb10b0ac88e34c3a066dc8ce283e9d2601c805ae71fc8dc9548fc0582.png:ro"
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - cache
      - seeder
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}/health_checks/default"]
      interval: 10s
      timeout: 3s
      retries: 3

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_START_PERIOD: 600
      AUTOHEAL_INTERVAL: 30

  worker:
    image: openproject/openproject:${TAG:-16-slim}
    restart: unless-stopped
    command: "./docker/prod/worker"
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-false}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-localhost:8080}"
      OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-false}"
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: ${RAILS_MIN_THREADS:-4}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-16}
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  cron:
    image: openproject/openproject:${TAG:-16-slim}
    restart: unless-stopped
    command: "./docker/prod/cron"
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-false}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-localhost:8080}"
      OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-false}"
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: ${RAILS_MIN_THREADS:-4}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-16}
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  seeder:
    image: openproject/openproject:${TAG:-16-slim}
    command: "./docker/prod/seeder"
    restart: on-failure
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-false}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-localhost:8080}"
      OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-false}"
      RAILS_CACHE_STORE: "memcache"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
      RAILS_MIN_THREADS: ${RAILS_MIN_THREADS:-4}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-16}
      IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
    networks:
      - backend
